[package]
name = "adapter_gamelog"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
regex = "1"
lazy_static = "1"
serde_json = "1"

[dev-dependencies]
# Test helpers
proptest = "1"
