[package]
name = "sc_manager_p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "1.0"
base64 = "0.21"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
