[package]
name = "sc_manager_persistence_postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sc_manager_core = { path = "../../services/core-domain" }

[dev-dependencies]
# Add DB test helpers here
