[package]
name = "sc_manager_adapter_discord"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
sc_manager_core = { path = "../../services/core-domain" }

[dev-dependencies]
# test helpers
